"""Build a Test-Case document (.docx) and attach it to a Jira ticket (MoM item 4).

WorkFlow 5 currently posts test cases as inline Jira wiki-markup. Per the MoM,
when a ticket reaches *Ready for QA* we now also produce a Word document and
attach it to the ticket, with a comment that links the attachment.

This keeps the existing inline comment (good for quick reading) and adds the
attachment + a short pointer comment. Public entry point:

    build_and_attach(issue_key, summary, testcases, phase="qa") -> dict

`phase` selects the flow: "qa" (Ready for QA, default) or "dev" (Code Review) —
which changes the filename, comment marker, document heading, and stage label so
a QA doc and a developer doc can coexist on the same ticket.
"""

from __future__ import annotations

import io
import os
from datetime import datetime, timezone
from typing import Any

import requests
from docx import Document
from docx.shared import Pt, RGBColor

def _get_jira_config() -> tuple[str, str, str]:
    from app.config import settings
    from app.app_settings import get_all_settings
    db_items = get_all_settings(settings)
    try:
        import psycopg2
        from psycopg2.extras import RealDictCursor
        with psycopg2.connect(settings.database_url) as conn:
            with conn.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute("SELECT key, value FROM app_user_settings WHERE key LIKE 'jira_%';")
                for r in cur.fetchall():
                    db_items[r["key"]] = r["value"]
    except Exception:
        pass

    url = (db_items.get("jira_base_url") or settings.jira_base_url or "").rstrip("/")
    email = db_items.get("jira_email") or settings.jira_email or ""
    token = db_items.get("jira_api_token") or settings.jira_api_token or ""
    return url, email, token

JIRA_TIMEOUT = 60

ATTACH_COMMENT_MARKER = "AI-GOVERNOR-TC-DOC-V1"
ATTACH_COMMENT_MARKER_DEV = "AI-GOVERNOR-TC-DOC-DEV-V1"


def _phase_meta(phase: str) -> dict[str, str]:
    """Labels/markers/filename suffix that vary between the QA and dev flows."""
    if phase == "dev":
        return {
            "marker": ATTACH_COMMENT_MARKER_DEV,
            "stage": "Code Review",
            "doc_heading": "Developer Test Cases",
            "filename": "dev_test_cases",
        }
    return {
        "marker": ATTACH_COMMENT_MARKER,
        "stage": "QA",
        "doc_heading": "Test Cases",
        "filename": "test_cases",
    }


def _normalise(testcases: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out = []
    for i, tc in enumerate(testcases, 1):
        out.append({
            "title": tc.get("title") or tc.get("name") or f"Test Case {i}",
            "steps": tc.get("steps") or [],
            "expected": tc.get("expected") or tc.get("expected_result") or "",
            "preconditions": tc.get("preconditions") or tc.get("precondition") or "",
            "priority": tc.get("priority") or "",
        })
    return out


def build_testcase_docx(
    issue_key: str, summary: str, testcases: list[dict[str, Any]], phase: str = "qa"
) -> bytes:
    """Render test cases to a styled .docx and return the bytes."""
    tcs = _normalise(testcases)
    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    h = doc.add_heading(f"{_phase_meta(phase)['doc_heading']} — {issue_key}", level=0)
    h.runs[0].font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)
    doc.add_paragraph(summary or "").italic = True
    meta = doc.add_paragraph()
    meta.add_run(
        f"Generated by AI Governor · {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC} · "
        f"{len(tcs)} test case(s)"
    ).font.size = Pt(9)

    for i, tc in enumerate(tcs, 1):
        doc.add_heading(f"TC {i}: {tc['title']}", level=2)
        if tc["priority"]:
            doc.add_paragraph(f"Priority: {tc['priority']}")
        if tc["preconditions"]:
            doc.add_paragraph(f"Preconditions: {tc['preconditions']}")
        if tc["steps"]:
            doc.add_paragraph("Steps:")
            for step in tc["steps"]:
                doc.add_paragraph(str(step), style="List Number")
        if tc["expected"]:
            p = doc.add_paragraph()
            p.add_run("Expected result: ").bold = True
            p.add_run(tc["expected"])

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def attach_to_jira(issue_key: str, filename: str, content: bytes) -> dict[str, Any]:
    """Upload a file to the Jira issue. Returns the created attachment metadata."""
    jira_base_url, jira_email, jira_token = _get_jira_config()
    url = f"{jira_base_url}/rest/api/3/issue/{issue_key}/attachments"
    resp = requests.post(
        url,
        auth=(jira_email, jira_token),
        headers={"X-Atlassian-Token": "no-check", "Accept": "application/json"},
        files={"file": (filename, content,
                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document")},
        timeout=JIRA_TIMEOUT,
    )
    resp.raise_for_status()
    data = resp.json()
    return data[0] if isinstance(data, list) and data else {}


def _existing_testcase_attachment(issue_key: str, filename: str) -> dict[str, Any] | None:
    """Return an already-attached test-case doc for this issue, if any."""
    jira_base_url, jira_email, jira_token = _get_jira_config()
    url = f"{jira_base_url}/rest/api/3/issue/{issue_key}"
    try:
        resp = requests.get(
            url,
            auth=(jira_email, jira_token),
            headers={"Accept": "application/json"},
            params={"fields": "attachment"},
            timeout=JIRA_TIMEOUT,
        )
        if resp.status_code >= 400:
            return None
        attachments = (resp.json().get("fields") or {}).get("attachment") or []
        for att in attachments:
            if att.get("filename") == filename:
                return att
    except requests.RequestException:
        return None
    return None


def _post_pointer_comment(
    issue_key: str, attachment: dict[str, Any], count: int, phase: str = "qa"
) -> bool:
    """A short comment linking the attached document (idempotent via marker)."""
    meta = _phase_meta(phase)
    marker = meta["marker"]
    jira_base_url, jira_email, jira_token = _get_jira_config()
    auth = (jira_email, jira_token)
    base = f"{jira_base_url}/rest/api/2/issue/{issue_key}/comment"
    att_id = attachment.get("id")
    fname = attachment.get("filename", "test-cases.docx")
    # Jira renders [^filename] as an inline link to the attachment.
    body = (
        f"h3. 🧪 Test cases attached ({count})\n"
        f"_Document generated by AI Governor on transition to *{meta['stage']}*._\n"
        f"{{anchor:{marker}}}\n\n"
        f"📎 [^{fname}]"
        + (f" (attachment id {att_id})" if att_id else "")
    )
    try:
        listing = requests.get(f"{base}?maxResults=100", auth=auth,
                               headers={"Accept": "application/json"}, timeout=JIRA_TIMEOUT)
        existing_id = None
        if listing.status_code < 400:
            for c in listing.json().get("comments", []):
                if marker in (c.get("body") or ""):
                    existing_id = c.get("id")
                    break
        method = requests.put if existing_id else requests.post
        target = f"{base}/{existing_id}" if existing_id else base
        resp = method(target, auth=auth,
                      headers={"Accept": "application/json", "Content-Type": "application/json"},
                      json={"body": body}, timeout=JIRA_TIMEOUT)
        return resp.status_code < 400
    except requests.RequestException:
        return False


def build_and_attach(
    issue_key: str,
    summary: str,
    testcases: list[dict[str, Any]],
    force: bool = False,
    phase: str = "qa",
) -> dict[str, Any]:
    if not testcases:
        return {"issueKey": issue_key, "attached": False, "reason": "no test cases"}
    filename = f"{issue_key}_{_phase_meta(phase)['filename']}.docx"
    if not force:
        existing = _existing_testcase_attachment(issue_key, filename)
        if existing:
            return {
                "issueKey": issue_key,
                "attached": False,
                "skipped": True,
                "reason": "test cases already attached",
                "attachmentId": existing.get("id"),
                "filename": filename,
            }
    content = build_testcase_docx(issue_key, summary, testcases, phase)
    attachment = attach_to_jira(issue_key, filename, content)
    commented = _post_pointer_comment(issue_key, attachment, len(testcases), phase)
    return {
        "issueKey": issue_key,
        "attached": bool(attachment),
        "attachmentId": attachment.get("id"),
        "filename": filename,
        "commentPosted": commented,
    }
